let lookup = {
    "abr": ["Abridger","http://id.loc.gov/vocabulary/relators/abr"],
    "acp": ["Art copyist","http://id.loc.gov/vocabulary/relators/acp"],
    "act": ["Actor","http://id.loc.gov/vocabulary/relators/act"],
    "adi": ["Art director","http://id.loc.gov/vocabulary/relators/adi"],
    "adp": ["Adapter","http://id.loc.gov/vocabulary/relators/adp"],
    "aft": ["Author of afterword, colophon, etc.","http://id.loc.gov/vocabulary/relators/aft"],
    "anl": ["Analyst","http://id.loc.gov/vocabulary/relators/anl"],
    "anm": ["Animator","http://id.loc.gov/vocabulary/relators/anm"],
    "ann": ["Annotator","http://id.loc.gov/vocabulary/relators/ann"],
    "ant": ["Bibliographic antecedent","http://id.loc.gov/vocabulary/relators/ant"],
    "ape": ["Appellee","http://id.loc.gov/vocabulary/relators/ape"],
    "apl": ["Appellant","http://id.loc.gov/vocabulary/relators/apl"],
    "app": ["Applicant","http://id.loc.gov/vocabulary/relators/app"],
    "aqt": ["Author in quotations or text abstracts","http://id.loc.gov/vocabulary/relators/aqt"],
    "arc": ["Architect","http://id.loc.gov/vocabulary/relators/arc"],
    "ard": ["Artistic director","http://id.loc.gov/vocabulary/relators/ard"],
    "arr": ["Arranger","http://id.loc.gov/vocabulary/relators/arr"],
    "art": ["Artist","http://id.loc.gov/vocabulary/relators/art"],
    "asg": ["Assignee","http://id.loc.gov/vocabulary/relators/asg"],
    "asn": ["Associated name","http://id.loc.gov/vocabulary/relators/asn"],
    "ato": ["Autographer","http://id.loc.gov/vocabulary/relators/ato"],
    "att": ["Attributed name","http://id.loc.gov/vocabulary/relators/att"],
    "auc": ["Auctioneer","http://id.loc.gov/vocabulary/relators/auc"],
    "aud": ["Author of dialog","http://id.loc.gov/vocabulary/relators/aud"],
    "aui": ["Author of introduction, etc.","http://id.loc.gov/vocabulary/relators/aui"],
    "aus": ["Screenwriter","http://id.loc.gov/vocabulary/relators/aus"],
    "aut": ["Author","http://id.loc.gov/vocabulary/relators/aut"],
    "bdd": ["Binding designer","http://id.loc.gov/vocabulary/relators/bdd"],
    "bjd": ["Bookjacket designer","http://id.loc.gov/vocabulary/relators/bjd"],
    "bkd": ["Book designer","http://id.loc.gov/vocabulary/relators/bkd"],
    "bkp": ["Book producer","http://id.loc.gov/vocabulary/relators/bkp"],
    "blw": ["Blurb writer","http://id.loc.gov/vocabulary/relators/blw"],
    "bnd": ["Binder","http://id.loc.gov/vocabulary/relators/bnd"],
    "bpd": ["Bookplate designer","http://id.loc.gov/vocabulary/relators/bpd"],
    "brd": ["Broadcaster","http://id.loc.gov/vocabulary/relators/brd"],
    "brl": ["Braille embosser","http://id.loc.gov/vocabulary/relators/brl"],
    "bsl": ["Bookseller","http://id.loc.gov/vocabulary/relators/bsl"],
    "cas": ["Caster","http://id.loc.gov/vocabulary/relators/cas"],
    "ccp": ["Conceptor","http://id.loc.gov/vocabulary/relators/ccp"],
    "chr": ["Choreographer","http://id.loc.gov/vocabulary/relators/chr"],
    "cli": ["Client","http://id.loc.gov/vocabulary/relators/cli"],
    "cll": ["Calligrapher","http://id.loc.gov/vocabulary/relators/cll"],
    "clr": ["Colorist","http://id.loc.gov/vocabulary/relators/clr"],
    "clt": ["Collotyper","http://id.loc.gov/vocabulary/relators/clt"],
    "cmm": ["Commentator","http://id.loc.gov/vocabulary/relators/cmm"],
    "cmp": ["Composer","http://id.loc.gov/vocabulary/relators/cmp"],
    "cmt": ["Compositor","http://id.loc.gov/vocabulary/relators/cmt"],
    "cnd": ["Conductor","http://id.loc.gov/vocabulary/relators/cnd"],
    "cng": ["Cinematographer","http://id.loc.gov/vocabulary/relators/cng"],
    "cns": ["Censor","http://id.loc.gov/vocabulary/relators/cns"],
    "coe": ["Contestant-appellee","http://id.loc.gov/vocabulary/relators/coe"],
    "col": ["Collector","http://id.loc.gov/vocabulary/relators/col"],
    "com": ["Compiler","http://id.loc.gov/vocabulary/relators/com"],
    "con": ["Conservator","http://id.loc.gov/vocabulary/relators/con"],
    "cor": ["Collection registrar","http://id.loc.gov/vocabulary/relators/cor"],
    "cos": ["Contestant","http://id.loc.gov/vocabulary/relators/cos"],
    "cot": ["Contestant-appellant","http://id.loc.gov/vocabulary/relators/cot"],
    "cou": ["Court governed","http://id.loc.gov/vocabulary/relators/cou"],
    "cov": ["Cover designer","http://id.loc.gov/vocabulary/relators/cov"],
    "cpc": ["Copyright claimant","http://id.loc.gov/vocabulary/relators/cpc"],
    "cpe": ["Complainant-appellee","http://id.loc.gov/vocabulary/relators/cpe"],
    "cph": ["Copyright holder","http://id.loc.gov/vocabulary/relators/cph"],
    "cpl": ["Complainant","http://id.loc.gov/vocabulary/relators/cpl"],
    "cpt": ["Complainant-appellant","http://id.loc.gov/vocabulary/relators/cpt"],
    "cre": ["Creator","http://id.loc.gov/vocabulary/relators/cre"],
    "crp": ["Correspondent","http://id.loc.gov/vocabulary/relators/crp"],
    "crr": ["Corrector","http://id.loc.gov/vocabulary/relators/crr"],
    "crt": ["Court reporter","http://id.loc.gov/vocabulary/relators/crt"],
    "csl": ["Consultant","http://id.loc.gov/vocabulary/relators/csl"],
    "csp": ["Consultant to a project","http://id.loc.gov/vocabulary/relators/csp"],
    "cst": ["Costume designer","http://id.loc.gov/vocabulary/relators/cst"],
    "ctb": ["Contributor","http://id.loc.gov/vocabulary/relators/ctb"],
    "cte": ["Contestee-appellee","http://id.loc.gov/vocabulary/relators/cte"],
    "ctg": ["Cartographer","http://id.loc.gov/vocabulary/relators/ctg"],
    "ctr": ["Contractor","http://id.loc.gov/vocabulary/relators/ctr"],
    "cts": ["Contestee","http://id.loc.gov/vocabulary/relators/cts"],
    "ctt": ["Contestee-appellant","http://id.loc.gov/vocabulary/relators/ctt"],
    "cur": ["Curator","http://id.loc.gov/vocabulary/relators/cur"],
    "cwt": ["Commentator for written text","http://id.loc.gov/vocabulary/relators/cwt"],
    "dbp": ["Distribution place","http://id.loc.gov/vocabulary/relators/dbp"],
    "dfd": ["Defendant","http://id.loc.gov/vocabulary/relators/dfd"],
    "dfe": ["Defendant-appellee","http://id.loc.gov/vocabulary/relators/dfe"],
    "dft": ["Defendant-appellant","http://id.loc.gov/vocabulary/relators/dft"],
    "dgg": ["Degree granting institution","http://id.loc.gov/vocabulary/relators/dgg"],
    "dgs": ["Degree supervisor","http://id.loc.gov/vocabulary/relators/dgs"],
    "dis": ["Dissertant","http://id.loc.gov/vocabulary/relators/dis"],
    "dln": ["Delineator","http://id.loc.gov/vocabulary/relators/dln"],
    "dnc": ["Dancer","http://id.loc.gov/vocabulary/relators/dnc"],
    "dnr": ["Donor","http://id.loc.gov/vocabulary/relators/dnr"],
    "dpc": ["Depicted","http://id.loc.gov/vocabulary/relators/dpc"],
    "dpt": ["Depositor","http://id.loc.gov/vocabulary/relators/dpt"],
    "drm": ["Draftsman","http://id.loc.gov/vocabulary/relators/drm"],
    "drt": ["Director","http://id.loc.gov/vocabulary/relators/drt"],
    "dsr": ["Designer","http://id.loc.gov/vocabulary/relators/dsr"],
    "dst": ["Distributor","http://id.loc.gov/vocabulary/relators/dst"],
    "dtc": ["Data contributor","http://id.loc.gov/vocabulary/relators/dtc"],
    "dte": ["Dedicatee","http://id.loc.gov/vocabulary/relators/dte"],
    "dtm": ["Data manager","http://id.loc.gov/vocabulary/relators/dtm"],
    "dto": ["Dedicator","http://id.loc.gov/vocabulary/relators/dto"],
    "dub": ["Dubious author","http://id.loc.gov/vocabulary/relators/dub"],
    "edc": ["Editor of compilation","http://id.loc.gov/vocabulary/relators/edc"],
    "edm": ["Editor of moving image work","http://id.loc.gov/vocabulary/relators/edm"],
    "edt": ["Editor","http://id.loc.gov/vocabulary/relators/edt"],
    "egr": ["Engraver","http://id.loc.gov/vocabulary/relators/egr"],
    "elg": ["Electrician","http://id.loc.gov/vocabulary/relators/elg"],
    "elt": ["Electrotyper","http://id.loc.gov/vocabulary/relators/elt"],
    "eng": ["Engineer","http://id.loc.gov/vocabulary/relators/eng"],
    "enj": ["Enacting jurisdiction","http://id.loc.gov/vocabulary/relators/enj"],
    "etr": ["Etcher","http://id.loc.gov/vocabulary/relators/etr"],
    "evp": ["Event place","http://id.loc.gov/vocabulary/relators/evp"],
    "exp": ["Expert","http://id.loc.gov/vocabulary/relators/exp"],
    "fac": ["Facsimilist","http://id.loc.gov/vocabulary/relators/fac"],
    "fds": ["Film distributor","http://id.loc.gov/vocabulary/relators/fds"],
    "fld": ["Field director","http://id.loc.gov/vocabulary/relators/fld"],
    "flm": ["Film editor","http://id.loc.gov/vocabulary/relators/flm"],
    "fmd": ["Film director","http://id.loc.gov/vocabulary/relators/fmd"],
    "fmk": ["Filmmaker","http://id.loc.gov/vocabulary/relators/fmk"],
    "fmo": ["Former owner","http://id.loc.gov/vocabulary/relators/fmo"],
    "fmp": ["Film producer","http://id.loc.gov/vocabulary/relators/fmp"],
    "fnd": ["Funder","http://id.loc.gov/vocabulary/relators/fnd"],
    "fpy": ["First party","http://id.loc.gov/vocabulary/relators/fpy"],
    "frg": ["Forger","http://id.loc.gov/vocabulary/relators/frg"],
    "gis": ["Geographic information specialist","http://id.loc.gov/vocabulary/relators/gis"],
    "his": ["Host institution","http://id.loc.gov/vocabulary/relators/his"],
    "hnr": ["Honoree","http://id.loc.gov/vocabulary/relators/hnr"],
    "hst": ["Host","http://id.loc.gov/vocabulary/relators/hst"],
    "ill": ["Illustrator","http://id.loc.gov/vocabulary/relators/ill"],
    "ilu": ["Illuminator","http://id.loc.gov/vocabulary/relators/ilu"],
    "ins": ["Inscriber","http://id.loc.gov/vocabulary/relators/ins"],
    "inv": ["Inventor","http://id.loc.gov/vocabulary/relators/inv"],
    "isb": ["Issuing body","http://id.loc.gov/vocabulary/relators/isb"],
    "itr": ["Instrumentalist","http://id.loc.gov/vocabulary/relators/itr"],
    "ive": ["Interviewee","http://id.loc.gov/vocabulary/relators/ive"],
    "ivr": ["Interviewer","http://id.loc.gov/vocabulary/relators/ivr"],
    "jud": ["Judge","http://id.loc.gov/vocabulary/relators/jud"],
    "jug": ["Jurisdiction governed","http://id.loc.gov/vocabulary/relators/jug"],
    "lbr": ["Laboratory","http://id.loc.gov/vocabulary/relators/lbr"],
    "lbt": ["Librettist","http://id.loc.gov/vocabulary/relators/lbt"],
    "ldr": ["Laboratory director","http://id.loc.gov/vocabulary/relators/ldr"],
    "led": ["Lead","http://id.loc.gov/vocabulary/relators/led"],
    "lee": ["Libelee-appellee","http://id.loc.gov/vocabulary/relators/lee"],
    "lel": ["Libelee","http://id.loc.gov/vocabulary/relators/lel"],
    "len": ["Lender","http://id.loc.gov/vocabulary/relators/len"],
    "let": ["Libelee-appellant","http://id.loc.gov/vocabulary/relators/let"],
    "lgd": ["Lighting designer","http://id.loc.gov/vocabulary/relators/lgd"],
    "lie": ["Libelant-appellee","http://id.loc.gov/vocabulary/relators/lie"],
    "lil": ["Libelant","http://id.loc.gov/vocabulary/relators/lil"],
    "lit": ["Libelant-appellant","http://id.loc.gov/vocabulary/relators/lit"],
    "lsa": ["Landscape architect","http://id.loc.gov/vocabulary/relators/lsa"],
    "lse": ["Licensee","http://id.loc.gov/vocabulary/relators/lse"],
    "lso": ["Licensor","http://id.loc.gov/vocabulary/relators/lso"],
    "ltg": ["Lithographer","http://id.loc.gov/vocabulary/relators/ltg"],
    "lyr": ["Lyricist","http://id.loc.gov/vocabulary/relators/lyr"],
    "mcp": ["Music copyist","http://id.loc.gov/vocabulary/relators/mcp"],
    "mdc": ["Metadata contact","http://id.loc.gov/vocabulary/relators/mdc"],
    "med": ["Medium","http://id.loc.gov/vocabulary/relators/med"],
    "mfp": ["Manufacture place","http://id.loc.gov/vocabulary/relators/mfp"],
    "mfr": ["Manufacturer","http://id.loc.gov/vocabulary/relators/mfr"],
    "mod": ["Moderator","http://id.loc.gov/vocabulary/relators/mod"],
    "mon": ["Monitor","http://id.loc.gov/vocabulary/relators/mon"],
    "mrb": ["Marbler","http://id.loc.gov/vocabulary/relators/mrb"],
    "mrk": ["Markup editor","http://id.loc.gov/vocabulary/relators/mrk"],
    "msd": ["Musical director","http://id.loc.gov/vocabulary/relators/msd"],
    "mte": ["Metal-engraver","http://id.loc.gov/vocabulary/relators/mte"],
    "mtk": ["Minute taker","http://id.loc.gov/vocabulary/relators/mtk"],
    "mus": ["Musician","http://id.loc.gov/vocabulary/relators/mus"],
    "nrt": ["Narrator","http://id.loc.gov/vocabulary/relators/nrt"],
    "opn": ["Opponent","http://id.loc.gov/vocabulary/relators/opn"],
    "org": ["Originator","http://id.loc.gov/vocabulary/relators/org"],
    "orm": ["Organizer","http://id.loc.gov/vocabulary/relators/orm"],
    "osp": ["Onscreen presenter","http://id.loc.gov/vocabulary/relators/osp"],
    "oth": ["Other","http://id.loc.gov/vocabulary/relators/oth"],
    "own": ["Owner","http://id.loc.gov/vocabulary/relators/own"],
    "pan": ["Panelist","http://id.loc.gov/vocabulary/relators/pan"],
    "pat": ["Patron","http://id.loc.gov/vocabulary/relators/pat"],
    "pbd": ["Publishing director","http://id.loc.gov/vocabulary/relators/pbd"],
    "pbl": ["Publisher","http://id.loc.gov/vocabulary/relators/pbl"],
    "pdr": ["Project director","http://id.loc.gov/vocabulary/relators/pdr"],
    "pfr": ["Proofreader","http://id.loc.gov/vocabulary/relators/pfr"],
    "pht": ["Photographer","http://id.loc.gov/vocabulary/relators/pht"],
    "plt": ["Platemaker","http://id.loc.gov/vocabulary/relators/plt"],
    "pma": ["Permitting agency","http://id.loc.gov/vocabulary/relators/pma"],
    "pmn": ["Production manager","http://id.loc.gov/vocabulary/relators/pmn"],
    "pop": ["Printer of plates","http://id.loc.gov/vocabulary/relators/pop"],
    "ppm": ["Papermaker","http://id.loc.gov/vocabulary/relators/ppm"],
    "ppt": ["Puppeteer","http://id.loc.gov/vocabulary/relators/ppt"],
    "pra": ["Praeses","http://id.loc.gov/vocabulary/relators/pra"],
    "prc": ["Process contact","http://id.loc.gov/vocabulary/relators/prc"],
    "prd": ["Production personnel","http://id.loc.gov/vocabulary/relators/prd"],
    "pre": ["Presenter","http://id.loc.gov/vocabulary/relators/pre"],
    "prf": ["Performer","http://id.loc.gov/vocabulary/relators/prf"],
    "prg": ["Programmer","http://id.loc.gov/vocabulary/relators/prg"],
    "prm": ["Printmaker","http://id.loc.gov/vocabulary/relators/prm"],
    "prn": ["Production company","http://id.loc.gov/vocabulary/relators/prn"],
    "pro": ["Producer","http://id.loc.gov/vocabulary/relators/pro"],
    "prp": ["Production place","http://id.loc.gov/vocabulary/relators/prp"],
    "prs": ["Production designer","http://id.loc.gov/vocabulary/relators/prs"],
    "prt": ["Printer","http://id.loc.gov/vocabulary/relators/prt"],
    "prv": ["Provider","http://id.loc.gov/vocabulary/relators/prv"],
    "pta": ["Patent applicant","http://id.loc.gov/vocabulary/relators/pta"],
    "pte": ["Plaintiff-appellee","http://id.loc.gov/vocabulary/relators/pte"],
    "ptf": ["Plaintiff","http://id.loc.gov/vocabulary/relators/ptf"],
    "pth": ["Patent holder","http://id.loc.gov/vocabulary/relators/pth"],
    "ptt": ["Plaintiff-appellant","http://id.loc.gov/vocabulary/relators/ptt"],
    "pup": ["Publication place","http://id.loc.gov/vocabulary/relators/pup"],
    "rbr": ["Rubricator","http://id.loc.gov/vocabulary/relators/rbr"],
    "rcd": ["Recordist","http://id.loc.gov/vocabulary/relators/rcd"],
    "rce": ["Recording engineer","http://id.loc.gov/vocabulary/relators/rce"],
    "rcp": ["Addressee","http://id.loc.gov/vocabulary/relators/rcp"],
    "rdd": ["Radio director","http://id.loc.gov/vocabulary/relators/rdd"],
    "red": ["Redaktor","http://id.loc.gov/vocabulary/relators/red"],
    "ren": ["Renderer","http://id.loc.gov/vocabulary/relators/ren"],
    "res": ["Researcher","http://id.loc.gov/vocabulary/relators/res"],
    "rev": ["Reviewer","http://id.loc.gov/vocabulary/relators/rev"],
    "rpc": ["Radio producer","http://id.loc.gov/vocabulary/relators/rpc"],
    "rps": ["Repository","http://id.loc.gov/vocabulary/relators/rps"],
    "rpt": ["Reporter","http://id.loc.gov/vocabulary/relators/rpt"],
    "rpy": ["Responsible party","http://id.loc.gov/vocabulary/relators/rpy"],
    "rse": ["Respondent-appellee","http://id.loc.gov/vocabulary/relators/rse"],
    "rsg": ["Restager","http://id.loc.gov/vocabulary/relators/rsg"],
    "rsp": ["Respondent","http://id.loc.gov/vocabulary/relators/rsp"],
    "rsr": ["Restorationist","http://id.loc.gov/vocabulary/relators/rsr"],
    "rst": ["Respondent-appellant","http://id.loc.gov/vocabulary/relators/rst"],
    "rth": ["Research team head","http://id.loc.gov/vocabulary/relators/rth"],
    "rtm": ["Research team member","http://id.loc.gov/vocabulary/relators/rtm"],
    "sad": ["Scientific advisor","http://id.loc.gov/vocabulary/relators/sad"],
    "sce": ["Scenarist","http://id.loc.gov/vocabulary/relators/sce"],
    "scl": ["Sculptor","http://id.loc.gov/vocabulary/relators/scl"],
    "scr": ["Scribe","http://id.loc.gov/vocabulary/relators/scr"],
    "sds": ["Sound designer","http://id.loc.gov/vocabulary/relators/sds"],
    "sec": ["Secretary","http://id.loc.gov/vocabulary/relators/sec"],
    "sgd": ["Stage director","http://id.loc.gov/vocabulary/relators/sgd"],
    "sgn": ["Signer","http://id.loc.gov/vocabulary/relators/sgn"],
    "sht": ["Supporting host","http://id.loc.gov/vocabulary/relators/sht"],
    "sll": ["Seller","http://id.loc.gov/vocabulary/relators/sll"],
    "sng": ["Singer","http://id.loc.gov/vocabulary/relators/sng"],
    "spk": ["Speaker","http://id.loc.gov/vocabulary/relators/spk"],
    "spn": ["Sponsor","http://id.loc.gov/vocabulary/relators/spn"],
    "spy": ["Second party","http://id.loc.gov/vocabulary/relators/spy"],
    "srv": ["Surveyor","http://id.loc.gov/vocabulary/relators/srv"],
    "std": ["Set designer","http://id.loc.gov/vocabulary/relators/std"],
    "stg": ["Setting","http://id.loc.gov/vocabulary/relators/stg"],
    "stl": ["Storyteller","http://id.loc.gov/vocabulary/relators/stl"],
    "stm": ["Stage manager","http://id.loc.gov/vocabulary/relators/stm"],
    "stn": ["Standards body","http://id.loc.gov/vocabulary/relators/stn"],
    "str": ["Stereotyper","http://id.loc.gov/vocabulary/relators/str"],
    "tcd": ["Technical director","http://id.loc.gov/vocabulary/relators/tcd"],
    "tch": ["Teacher","http://id.loc.gov/vocabulary/relators/tch"],
    "ths": ["Thesis advisor","http://id.loc.gov/vocabulary/relators/ths"],
    "tld": ["Television director","http://id.loc.gov/vocabulary/relators/tld"],
    "tlp": ["Television producer","http://id.loc.gov/vocabulary/relators/tlp"],
    "trc": ["Transcriber","http://id.loc.gov/vocabulary/relators/trc"],
    "trl": ["Translator","http://id.loc.gov/vocabulary/relators/trl"],
    "tyd": ["Type designer","http://id.loc.gov/vocabulary/relators/tyd"],
    "tyg": ["Typographer","http://id.loc.gov/vocabulary/relators/tyg"],
    "uvp": ["University place","http://id.loc.gov/vocabulary/relators/uvp"],
    "vac": ["Voice actor","http://id.loc.gov/vocabulary/relators/vac"],
    "vdg": ["Videographer","http://id.loc.gov/vocabulary/relators/vdg"],
    "wac": ["Writer of added commentary","http://id.loc.gov/vocabulary/relators/wac"],
    "wal": ["Writer of added lyrics","http://id.loc.gov/vocabulary/relators/wal"],
    "wam": ["Writer of accompanying material","http://id.loc.gov/vocabulary/relators/wam"],
    "wat": ["Writer of added text","http://id.loc.gov/vocabulary/relators/wat"],
    "wdc": ["Woodcutter","http://id.loc.gov/vocabulary/relators/wdc"],
    "wde": ["Wood engraver","http://id.loc.gov/vocabulary/relators/wde"],
    "win": ["Writer of introduction","http://id.loc.gov/vocabulary/relators/win"],
    "wit": ["Witness","http://id.loc.gov/vocabulary/relators/wit"],
    "wpr": ["Writer of preface","http://id.loc.gov/vocabulary/relators/wpr"],
    "wst": ["Writer of supplementary textual content","http://id.loc.gov/vocabulary/relators/wst"]
};


export function relator_lookup(key) {
    return lookup[key];
}